### ISSUE TITLE
Поддержка дисплеев с 6 знакоместами

### ISSUE THREAD

**Issue by twoporylyj** [GyverLibs/GyverTM1637#2]
Здравствуйте. Планируется ли поддержка дисплеев с 6 знакоместами? Ноги для этого у драйвера есть. Спасибо.

**Comment by GyverLibs** [comment]
Привет, можно ссылку? Вообще эта библиотека заброшена, поддержка новых будет в библиотеке sevenSegments

**Comment by twoporylyj** [comment]
Только будет? Ещё нет?

**Comment by GyverLibs** [comment]
Ну я попросил ссылку на дисплей, значит вообще не понимаю о чем речь)

**Comment by twoporylyj** [comment]
Дисплей с TM1637 на 4 знакоместа готовый с алика, к нему на проводах припараллелил ещё два знакоместа, обнаружил, что ноги 10 и 11 у микросхемы ещё не задействованы, на них общие аноды дополнительных индикаторов и прицепил.

**Comment by GyverLibs** [comment]
Ууу, поддержку хендмейда и кастома не обещаю. Библой занимается другой человек, черкну ему

**Comment by twoporylyj** [comment]
Всё стандартно, только у микросхемы не 4, а все 6 анодных ног теперь задействовано.

**Comment by GyverLibs** [comment]
Ну так библиотека не под микросхему, а под конкретный модуль

**Comment by twoporylyj** [comment]
В общем, до переделки в 6-знакоместный он выглядел так:

https://www.youbot.ru/product/svetodiodnyy-displey-tm1637-zelenyy?ymclid=16372330048964376395200002

**Comment by bamboo-master** [comment]
Я точно знаю как переделать обычную Grove_4-Digit_Display
В этой не все понятно.
Попробуйте изменить конструкцию "byte i = 0; i < 4; i ++" на "byte i = 0; i < 6; i ++" 
После чего создайте свой void или измените какой-нибудь. Например:
    void displayClock(uint8_t hrs, uint8_t mins, uint8_t secs);		
Может и прокатит, я не проверял, мне не к чему сейчас.

**Comment by bamboo-master** [comment]
https://github.com/bamboo-master/GyverTM1637_6_digit

**Comment by GyverLibs** [comment]
Фича есть в библиотеке GyverSegment
