### ISSUE TITLE
Опрос клавиатуры

### ISSUE THREAD

**Issue by axnw83** [GyverLibs/GyverTM1637#4]
Зравствуйте, Алекс.
ТМ1637 поддерживает сканирование 16 клавиш по даташиту. Можно ли допилить библиотеку для полного функционала микросхемы? Сразу и дисплей и кнопки на одной микросхеме (например часы с 6-ю 7-ми индикаторами и кнопки управления)
Для примера модуль:
https://fr.aliexpress.com/item/32957227249.html?spm=a2g0o.productlist.0.0.589c761eeICzqO&algo_pvid=14c27c46-760f-4172-9925-fab66ccfb5c6&algo_exp_id=14c27c46-760f-4172-9925-fab66ccfb5c6-13&pdp_ext_f=%7B%22sku_id%22%3A%22-1%22%7D&pdp_pi=-1%3B15.21%3B-1%3B-1%40unknownPrice%3BUAH%3Bsearch-mainSearch

**Comment by GyverLibs** [comment]
Привет, проще написать новую
